param(
    [string[]]$SegmentReviewPaths = @(
        "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\ssj_ep01_sc01_consistency_review.json",
        "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\ssj_ep01_sc02_consistency_review.json",
        "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\ssj_ep01_sc03_consistency_review.json",
        "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\ssj_ep01_sc04_consistency_review.json"
    ),
    [string]$SandboxDir = "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\sandbox_ep01_human_review_branches",
    [string]$SandboxOutputDir = "G:\ComfyUI\output\AIShortDrama\episodes\sandbox_ep01_human_review_branches",
    [string]$ResultPath = "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\ep01_human_review_branch_test_result.json",
    [string]$PythonPath = "python",
    [switch]$SkipFormalCutBuild
)

$scriptsDir = "E:\workspace\ComfyUIProjects\Movie-Generation\scripts"
$applyScript = Join-Path $scriptsDir "apply_ep01_human_review_decisions.ps1"
$gateScript = Join-Path $scriptsDir "test_ep01_formal_cut_gate.ps1"
$formalCutScript = Join-Path $scriptsDir "build_ep01_formal_cut.ps1"
$queueScript = Join-Path $scriptsDir "build_human_review_regeneration_queue.ps1"
$runnerScript = Join-Path $scriptsDir "run_regeneration_queue.ps1"
$probeScript = Join-Path $scriptsDir "probe_video_cv2.py"

if (Test-Path -LiteralPath $SandboxDir) {
    Remove-Item -LiteralPath $SandboxDir -Recurse -Force
}
if (Test-Path -LiteralPath $SandboxOutputDir) {
    Remove-Item -LiteralPath $SandboxOutputDir -Recurse -Force
}
New-Item -ItemType Directory -Path $SandboxDir -Force | Out-Null
New-Item -ItemType Directory -Path $SandboxOutputDir -Force | Out-Null

function Get-Review-Id {
    param($Review, [string]$Path)

    if ($Review.segment_id) {
        $segmentId = [string]$Review.segment_id
        if ($segmentId -match "(SSJ_EP01_SC\d+)") {
            return $Matches[1]
        }
        return $segmentId
    }
    if ([System.IO.Path]::GetFileNameWithoutExtension($Path) -match "(ssj_ep01_sc\d+)") {
        return $Matches[1].ToUpperInvariant()
    }
    return [System.IO.Path]::GetFileNameWithoutExtension($Path).ToUpperInvariant()
}

function Copy-Reviews {
    param([string]$Prefix)

    $paths = @()
    foreach ($path in $SegmentReviewPaths) {
        if (-not (Test-Path -LiteralPath $path)) {
            throw "Review file not found: $path"
        }
        $name = [System.IO.Path]::GetFileName($path)
        $dest = Join-Path $SandboxDir "$Prefix$name"
        Copy-Item -LiteralPath $path -Destination $dest -Force
        $paths += $dest
    }
    return $paths
}

function New-DecisionFile {
    param(
        [string[]]$ReviewPaths,
        [string]$Path,
        [string]$DefaultDecision,
        [string]$Reason,
        [hashtable]$Overrides = @{}
    )

    $items = @()
    foreach ($reviewPath in $ReviewPaths) {
        $review = Get-Content -LiteralPath $reviewPath -Raw -Encoding UTF8 | ConvertFrom-Json
        $reviewId = Get-Review-Id -Review $review -Path $reviewPath
        foreach ($shot in @($review.shots)) {
            $key = "$reviewId|$($shot.shot_id)"
            $decision = $DefaultDecision
            $scope = "video"
            $itemReason = $Reason
            $notes = "Sandbox branch test generated decision."
            if ($Overrides.ContainsKey($key)) {
                $override = $Overrides[$key]
                if ($override.decision) { $decision = [string]$override.decision }
                if ($override.scope) { $scope = [string]$override.scope }
                if ($override.reason) { $itemReason = [string]$override.reason }
                if ($override.notes) { $notes = [string]$override.notes }
            }
            $items += [ordered]@{
                review_id = $reviewId
                review_path = $reviewPath
                shot_id = [string]$shot.shot_id
                title = if ($shot.title) { [string]$shot.title } else { "" }
                current_status = if ($shot.status) { [string]$shot.status } else { "" }
                decision = $decision
                regeneration_scope = $scope
                reason = $itemReason
                notes = $notes
            }
        }
    }

    $payload = [ordered]@{
        updated = (Get-Date).ToString("s")
        reviewer = "sandbox_branch_test"
        instructions = "Synthetic decision file generated by test_ep01_human_review_branches.ps1."
        decisions = $items
    }
    $payload | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $Path -Encoding UTF8
    return $payload
}

function Convert-OutputJson {
    param($Output)

    $text = ($Output | Out-String).Trim()
    if (-not $text) {
        return $null
    }
    try {
        return ($text | ConvertFrom-Json)
    } catch {
        return [pscustomobject]@{
            ok = $false
            parse_error = $_.Exception.Message
            raw_tail = ($text -split "`r?`n" | Select-Object -Last 20)
        }
    }
}

function Invoke-Step {
    param(
        [string]$Name,
        [string]$ScriptPath,
        [string[]]$Arguments = @(),
        [switch]$AllowNonZero
    )

    $output = & powershell -ExecutionPolicy Bypass -File $ScriptPath @Arguments 2>&1
    $exitCode = $LASTEXITCODE
    return [ordered]@{
        name = $Name
        script = $ScriptPath
        arguments = $Arguments
        exit_code = $exitCode
        ok = ($exitCode -eq 0 -or [bool]$AllowNonZero)
        parsed = Convert-OutputJson -Output $output
        output_tail = @($output | Select-Object -Last 16)
    }
}

function Join-Args {
    param([object[]]$Parts)

    $args = @()
    foreach ($part in $Parts) {
        if ($null -eq $part) {
            continue
        }
        if ($part -is [System.Array]) {
            foreach ($item in $part) {
                $args += [string]$item
            }
        } else {
            $args += [string]$part
        }
    }
    return [string[]]$args
}

function Invoke-External {
    param([string]$Name, [scriptblock]$Block, [switch]$AllowNonZero)

    $output = & $Block 2>&1
    $exitCode = $LASTEXITCODE
    return [ordered]@{
        name = $Name
        exit_code = $exitCode
        ok = ($exitCode -eq 0 -or [bool]$AllowNonZero)
        parsed = Convert-OutputJson -Output $output
        output_tail = @($output | Select-Object -Last 16)
    }
}

function ConvertTo-PowerShellSingleQuotedString {
    param([string]$Text)

    return "'" + ($Text -replace "'", "''") + "'"
}

function ConvertTo-PowerShellArrayLiteral {
    param([string[]]$Items)

    if (-not $Items -or @($Items).Count -eq 0) {
        return "@()"
    }
    $quoted = @($Items | ForEach-Object { ConvertTo-PowerShellSingleQuotedString -Text $_ })
    return "@(" + ($quoted -join ", ") + ")"
}

function Invoke-CommandTextStep {
    param(
        [string]$Name,
        [string]$Command,
        [switch]$AllowNonZero
    )

    $output = & powershell -NoProfile -ExecutionPolicy Bypass -Command $Command 2>&1
    $exitCode = $LASTEXITCODE
    return [ordered]@{
        name = $Name
        command = $Command
        exit_code = $exitCode
        ok = ($exitCode -eq 0 -or [bool]$AllowNonZero)
        parsed = Convert-OutputJson -Output $output
        output_tail = @($output | Select-Object -Last 16)
    }
}

function Test-BranchSuccess {
    param($Step)

    return ($Step -and [bool]$Step.ok)
}

$allPass = [ordered]@{
    ok = $false
    steps = @()
}
$regen = [ordered]@{
    ok = $false
    steps = @()
}

try {
    $allPassReviews = @(Copy-Reviews -Prefix "allpass_")
    $allPassDecisionPath = Join-Path $SandboxDir "allpass_human_review_decisions_ep01.json"
    New-DecisionFile -ReviewPaths $allPassReviews -Path $allPassDecisionPath -DefaultDecision "pass" -Reason "Sandbox all-pass branch validation." | Out-Null

    $allPassApplyPath = Join-Path $SandboxDir "allpass_apply_result.json"
    $allPassApplyCommand = @(
        "`$reviews = $(ConvertTo-PowerShellArrayLiteral -Items $allPassReviews)",
        "& $(ConvertTo-PowerShellSingleQuotedString -Text $applyScript) -DecisionPath $(ConvertTo-PowerShellSingleQuotedString -Text $allPassDecisionPath) -ReviewPaths `$reviews -ResultPath $(ConvertTo-PowerShellSingleQuotedString -Text $allPassApplyPath)",
        'exit $LASTEXITCODE'
    ) -join "; "
    $allPass.steps += Invoke-CommandTextStep -Name "allpass_apply_decisions" -Command $allPassApplyCommand

    $allPassGatePath = Join-Path $SandboxDir "allpass_formal_gate.json"
    $allPassGateCommand = @(
        "`$reviews = $(ConvertTo-PowerShellArrayLiteral -Items $allPassReviews)",
        "& $(ConvertTo-PowerShellSingleQuotedString -Text $gateScript) -ReviewPaths `$reviews -ResultPath $(ConvertTo-PowerShellSingleQuotedString -Text $allPassGatePath) -PythonPath $(ConvertTo-PowerShellSingleQuotedString -Text $PythonPath) -VideoProbePath $(ConvertTo-PowerShellSingleQuotedString -Text $probeScript) -SkipSegmentCutChecks",
        'exit $LASTEXITCODE'
    ) -join "; "
    $allPass.steps += Invoke-CommandTextStep -Name "allpass_formal_gate" -Command $allPassGateCommand

    $allPassGate = Get-Content -LiteralPath $allPassGatePath -Raw -Encoding UTF8 | ConvertFrom-Json
    $allPass.formal_gate_ok = [bool]$allPassGate.ok
    $allPass.formal_gate_failure_count = [int]$allPassGate.failure_count

    if (-not $SkipFormalCutBuild) {
        $segmentOutputs = @(
            (Join-Path $SandboxOutputDir "SSJ_EP01_SC01_formal_cut_sandbox.mp4"),
            (Join-Path $SandboxOutputDir "SSJ_EP01_SC02_formal_cut_sandbox.mp4"),
            (Join-Path $SandboxOutputDir "SSJ_EP01_SC03_formal_cut_sandbox.mp4"),
            (Join-Path $SandboxOutputDir "SSJ_EP01_SC04_formal_cut_sandbox.mp4")
        )
        $formalOutput = Join-Path $SandboxOutputDir "SSJ_EP01_formal_cut_sandbox_allpass.mp4"
        $formalBuildResult = Join-Path $SandboxDir "allpass_formal_cut_build_result.json"
        $formalBuildGate = Join-Path $SandboxDir "allpass_formal_cut_gate_check.json"
        $formalPostGate = Join-Path $SandboxDir "allpass_formal_cut_postbuild_gate_check.json"
        $assemblyReview = Join-Path $SandboxDir "allpass_formal_cut_review.json"
        $assemblyManifest = Join-Path $SandboxDir "allpass_formal_cut_result.json"
        $formalCommand = @(
            "`$reviews = $(ConvertTo-PowerShellArrayLiteral -Items $allPassReviews)",
            "`$segments = $(ConvertTo-PowerShellArrayLiteral -Items $segmentOutputs)",
            "& $(ConvertTo-PowerShellSingleQuotedString -Text $formalCutScript) -ReviewPaths `$reviews -SegmentOutputPaths `$segments -OutputPath $(ConvertTo-PowerShellSingleQuotedString -Text $formalOutput) -ResultPath $(ConvertTo-PowerShellSingleQuotedString -Text $formalBuildResult) -GatePath $(ConvertTo-PowerShellSingleQuotedString -Text $formalBuildGate) -PostBuildGatePath $(ConvertTo-PowerShellSingleQuotedString -Text $formalPostGate) -AssemblyReviewPath $(ConvertTo-PowerShellSingleQuotedString -Text $assemblyReview) -AssemblyManifestPath $(ConvertTo-PowerShellSingleQuotedString -Text $assemblyManifest) -SegmentManifestDir $(ConvertTo-PowerShellSingleQuotedString -Text $SandboxDir) -SegmentManifestPrefix 'allpass_' -PythonPath $(ConvertTo-PowerShellSingleQuotedString -Text $PythonPath)",
            'exit $LASTEXITCODE'
        ) -join "; "
        $allPass.steps += Invoke-CommandTextStep -Name "allpass_build_formal_cut" -Command $formalCommand

        $probeOutput = & $PythonPath $probeScript $formalOutput
        $probeExit = $LASTEXITCODE
        $probe = Convert-OutputJson -Output $probeOutput
        $allPass.final_output = $formalOutput
        $allPass.final_probe = $probe
        $allPass.final_probe_exit_code = $probeExit
    }

    $lastAllPassStep = $allPass.steps[-1]
    $allPass.ok = [bool]($allPass.formal_gate_ok -and ($SkipFormalCutBuild -or ((Test-BranchSuccess -Step $lastAllPassStep) -and $allPass.final_probe -and $allPass.final_probe.ok)))
} catch {
    $allPass.error = $_.Exception.Message
}

try {
    $regenReviews = @(Copy-Reviews -Prefix "regen_")
    $regenDecisionPath = Join-Path $SandboxDir "regen_human_review_decisions_ep01.json"
    $override = @{
        "SSJ_EP01_SC04|TEST_SSJ_EP01_SC04_SH02" = [pscustomobject]@{
            decision = "needs_regeneration"
            scope = "video"
            reason = "Sandbox regeneration branch validation."
            notes = "Expected to select SC04 SH02 final I2V workflow."
        }
    }
    New-DecisionFile -ReviewPaths $regenReviews -Path $regenDecisionPath -DefaultDecision "pending" -Reason "" -Overrides $override | Out-Null

    $queuePath = Join-Path $SandboxDir "regen_queue_ep01.json"
    $regenQueueCommand = @(
        "`$reviews = $(ConvertTo-PowerShellArrayLiteral -Items $regenReviews)",
        "& $(ConvertTo-PowerShellSingleQuotedString -Text $queueScript) -ReviewPaths `$reviews -DecisionPath $(ConvertTo-PowerShellSingleQuotedString -Text $regenDecisionPath) -QueuePath $(ConvertTo-PowerShellSingleQuotedString -Text $queuePath)",
        'exit $LASTEXITCODE'
    ) -join "; "
    $regen.steps += Invoke-CommandTextStep -Name "regen_build_queue" -Command $regenQueueCommand
    $queue = Get-Content -LiteralPath $queuePath -Raw -Encoding UTF8 | ConvertFrom-Json
    $regen.queue_count = [int]$queue.queue_count
    $regen.queue_selected_workflow = if (@($queue.queue).Count -gt 0) { [string]$queue.queue[0].selected_workflow } else { "" }
    $regen.queue_can_auto_rerun = if (@($queue.queue).Count -gt 0) { [bool]$queue.queue[0].can_auto_rerun } else { $false }

    $dryRunResultPath = Join-Path $SandboxDir "regen_queue_dry_run_result.json"
    $regen.steps += Invoke-Step -Name "regen_runner_dry_run" -ScriptPath $runnerScript -Arguments @("-QueuePath", $queuePath, "-ResultPath", $dryRunResultPath, "-DryRun", "-MaxItems", "1")
    $dryRun = Get-Content -LiteralPath $dryRunResultPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $regen.dry_run_count = @($dryRun.runs).Count
    $regen.dry_run_command = if (@($dryRun.runs).Count -gt 0) { [string]$dryRun.runs[0].command } else { "" }
    $regen.ok = [bool]($regen.queue_count -eq 1 -and $regen.queue_can_auto_rerun -and (Test-Path -LiteralPath $regen.queue_selected_workflow) -and $regen.dry_run_count -eq 1)
} catch {
    $regen.error = $_.Exception.Message
}

$result = [ordered]@{
    updated = (Get-Date).ToString("s")
    sandbox_dir = $SandboxDir
    sandbox_output_dir = $SandboxOutputDir
    skip_formal_cut_build = [bool]$SkipFormalCutBuild
    all_pass_branch = $allPass
    regeneration_branch = $regen
    ok = [bool]($allPass.ok -and $regen.ok)
}

New-Item -ItemType Directory -Path (Split-Path $ResultPath) -Force | Out-Null
$result | ConvertTo-Json -Depth 40 | Set-Content -LiteralPath $ResultPath -Encoding UTF8
$result | ConvertTo-Json -Depth 40

if (-not $result.ok) {
    exit 1
}
