param(
    [string[]]$ReviewPaths = @(
        "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\ssj_ep02_sc01_storyboard_review.json"
    ),
    [string]$SandboxDir = "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\sandbox_storyboard_review_branches",
    [string]$ResultPath = "E:\workspace\ComfyUIProjects\Movie-Generation\manifests\storyboard_review_branch_test_result.json"
)

$scriptsDir = "E:\workspace\ComfyUIProjects\Movie-Generation\scripts"
$precheckScript = Join-Path $scriptsDir "test_storyboard_review_decisions.ps1"
$queueScript = Join-Path $scriptsDir "build_storyboard_i2v_queue.ps1"
$runnerScript = Join-Path $scriptsDir "run_storyboard_i2v_queue.ps1"

if (Test-Path -LiteralPath $SandboxDir) {
    Remove-Item -LiteralPath $SandboxDir -Recurse -Force
}
New-Item -ItemType Directory -Path $SandboxDir -Force | Out-Null

function Copy-Reviews {
    param([string]$Prefix)

    $paths = @()
    foreach ($path in $ReviewPaths) {
        if (-not (Test-Path -LiteralPath $path)) {
            throw "Review file not found: $path"
        }
        $name = [System.IO.Path]::GetFileName($path)
        $dest = Join-Path $SandboxDir "$Prefix$name"
        Copy-Item -LiteralPath $path -Destination $dest -Force
        $paths += $dest
    }
    return [string[]]$paths
}

function Get-Review-Id {
    param($Review, [string]$Path)

    if ($Review.segment_id) {
        return [string]$Review.segment_id
    }
    return [System.IO.Path]::GetFileNameWithoutExtension($Path).ToUpperInvariant()
}

function New-DecisionFile {
    param(
        [string[]]$ReviewPaths,
        [string]$Path,
        [string]$DefaultDecision,
        [hashtable]$Overrides = @{}
    )

    $items = @()
    foreach ($reviewPath in $ReviewPaths) {
        $review = Get-Content -LiteralPath $reviewPath -Raw -Encoding UTF8 | ConvertFrom-Json
        $reviewId = Get-Review-Id -Review $review -Path $reviewPath
        foreach ($shot in @($review.shots)) {
            $key = "$reviewId|$($shot.shot_id)"
            $decisionValue = $DefaultDecision
            $reason = ""
            $notes = "Sandbox storyboard branch test generated decision."
            if ($Overrides.ContainsKey($key)) {
                $override = $Overrides[$key]
                if ($override.decision) { $decisionValue = [string]$override.decision }
                if ($override.reason) { $reason = [string]$override.reason }
                if ($override.notes) { $notes = [string]$override.notes }
            }
            $items += [ordered]@{
                review_id = $reviewId
                review_path = $reviewPath
                review_package_markdown = ""
                shot_id = [string]$shot.shot_id
                title = if ($shot.title) { [string]$shot.title } else { "" }
                current_status = if ($shot.status) { [string]$shot.status } else { "" }
                storyboard_path = if ($shot.storyboard_path) { [string]$shot.storyboard_path } else { "" }
                storyboard_workflow = if ($shot.storyboard_workflow) { [string]$shot.storyboard_workflow } else { "" }
                video_workflow = if ($shot.video_workflow) { [string]$shot.video_workflow } else { "" }
                decision = $decisionValue
                reason = $reason
                notes = $notes
            }
        }
    }

    $payload = [ordered]@{
        updated = (Get-Date).ToString("s")
        reviewer = "sandbox_storyboard_branch_test"
        instructions = "Synthetic storyboard decision file generated by test_storyboard_review_branches.ps1."
        decisions = $items
    }
    $payload | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $Path -Encoding UTF8
    return $payload
}

function Invoke-Step {
    param(
        [string]$Name,
        [string]$ScriptPath,
        [string[]]$Arguments = @()
    )

    $output = & powershell -ExecutionPolicy Bypass -File $ScriptPath @Arguments 2>&1
    $exitCode = $LASTEXITCODE
    return [ordered]@{
        name = $Name
        script = $ScriptPath
        arguments = $Arguments
        exit_code = $exitCode
        ok = ($exitCode -eq 0)
        output_tail = @($output | Select-Object -Last 18)
    }
}

function Review-Args {
    param([string[]]$Paths)

    $args = @("-ReviewPaths")
    foreach ($path in $Paths) {
        $args += $path
    }
    return [string[]]$args
}

$allPass = [ordered]@{ ok = $false; steps = @() }
$regen = [ordered]@{ ok = $false; steps = @() }

try {
    $allPassReviews = Copy-Reviews -Prefix "allpass_"
    $allPassDecision = Join-Path $SandboxDir "allpass_storyboard_decisions.json"
    $allPassQueue = Join-Path $SandboxDir "allpass_storyboard_i2v_queue.json"
    $allPassRun = Join-Path $SandboxDir "allpass_storyboard_i2v_queue_dry_run.json"
    New-DecisionFile -ReviewPaths $allPassReviews -Path $allPassDecision -DefaultDecision "pass" | Out-Null

    $reviewArgs = Review-Args -Paths $allPassReviews
    $allPassPrecheckArgs = @("-DecisionPath", $allPassDecision, "-ResultPath", (Join-Path $SandboxDir "allpass_precheck.json")) + $reviewArgs
    $allPassQueueArgs = @("-DecisionPath", $allPassDecision, "-QueuePath", $allPassQueue) + $reviewArgs
    $allPass.steps += Invoke-Step -Name "allpass_precheck" -ScriptPath $precheckScript -Arguments $allPassPrecheckArgs
    $allPass.steps += Invoke-Step -Name "allpass_build_queue" -ScriptPath $queueScript -Arguments $allPassQueueArgs
    $allPass.steps += Invoke-Step -Name "allpass_queue_dry_run" -ScriptPath $runnerScript -Arguments @("-QueuePath", $allPassQueue, "-ResultPath", $allPassRun, "-DryRun")

    $queue = Get-Content -LiteralPath $allPassQueue -Raw -Encoding UTF8 | ConvertFrom-Json
    $dryRun = Get-Content -LiteralPath $allPassRun -Raw -Encoding UTF8 | ConvertFrom-Json
    $allPass.queue_count = [int]$queue.queue_count
    $allPass.dry_run_count = @($dryRun.runs).Count
    $allPass.ok = [bool]((@($allPass.steps | Where-Object { -not $_.ok }).Count -eq 0) -and $allPass.queue_count -eq 3 -and $allPass.dry_run_count -eq 3)
} catch {
    $allPass.error = $_.Exception.Message
}

try {
    $regenReviews = Copy-Reviews -Prefix "regen_"
    $regenDecision = Join-Path $SandboxDir "regen_storyboard_decisions.json"
    $regenQueue = Join-Path $SandboxDir "regen_storyboard_i2v_queue.json"
    $regenRun = Join-Path $SandboxDir "regen_storyboard_i2v_queue_dry_run.json"
    $override = @{
        "SSJ_EP02_SC01|TEST_SSJ_EP02_SC01_SH02" = [pscustomobject]@{
            decision = "needs_regeneration"
            reason = "Sandbox storyboard regeneration branch validation."
            notes = "Expected to select SH02 storyboard workflow."
        }
    }
    New-DecisionFile -ReviewPaths $regenReviews -Path $regenDecision -DefaultDecision "pending" -Overrides $override | Out-Null

    $reviewArgs = Review-Args -Paths $regenReviews
    $regenPrecheckArgs = @("-DecisionPath", $regenDecision, "-ResultPath", (Join-Path $SandboxDir "regen_precheck.json")) + $reviewArgs
    $regenQueueArgs = @("-DecisionPath", $regenDecision, "-QueuePath", $regenQueue) + $reviewArgs
    $regen.steps += Invoke-Step -Name "regen_precheck" -ScriptPath $precheckScript -Arguments $regenPrecheckArgs
    $regen.steps += Invoke-Step -Name "regen_build_queue" -ScriptPath $queueScript -Arguments $regenQueueArgs
    $regen.steps += Invoke-Step -Name "regen_queue_dry_run" -ScriptPath $runnerScript -Arguments @("-QueuePath", $regenQueue, "-ResultPath", $regenRun, "-DryRun")

    $queue = Get-Content -LiteralPath $regenQueue -Raw -Encoding UTF8 | ConvertFrom-Json
    $dryRun = Get-Content -LiteralPath $regenRun -Raw -Encoding UTF8 | ConvertFrom-Json
    $first = if (@($queue.queue).Count -gt 0) { $queue.queue[0] } else { $null }
    $regen.queue_count = [int]$queue.queue_count
    $regen.action = if ($first) { [string]$first.action } else { "" }
    $regen.selected_workflow = if ($first) { [string]$first.selected_workflow } else { "" }
    $regen.dry_run_count = @($dryRun.runs).Count
    $regen.ok = [bool]((@($regen.steps | Where-Object { -not $_.ok }).Count -eq 0) -and $regen.queue_count -eq 1 -and $regen.action -eq "regenerate_storyboard" -and (Test-Path -LiteralPath $regen.selected_workflow) -and $regen.dry_run_count -eq 1)
} catch {
    $regen.error = $_.Exception.Message
}

$result = [ordered]@{
    updated = (Get-Date).ToString("s")
    sandbox_dir = $SandboxDir
    all_pass_branch = $allPass
    regeneration_branch = $regen
    ok = [bool]($allPass.ok -and $regen.ok)
}

New-Item -ItemType Directory -Path (Split-Path $ResultPath) -Force | Out-Null
$result | ConvertTo-Json -Depth 40 | Set-Content -LiteralPath $ResultPath -Encoding UTF8
$result | ConvertTo-Json -Depth 40

if (-not $result.ok) {
    exit 1
}
